# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.IntegerField()),
                ('fans', models.IntegerField()),
                ('show', models.IntegerField()),
                ('time', models.DateField()),
                ('used', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('d_no', models.CharField(max_length=64, unique=True)),
                ('d_id', models.CharField(max_length=64, unique=True)),
                ('d_shop_name', models.CharField(max_length=128, unique=True)),
                ('d_area', models.CharField(max_length=128)),
                ('d_address', models.CharField(max_length=128)),
                ('d_shop_contact', models.CharField(max_length=128)),
                ('d_shop_tel', models.CharField(max_length=128)),
                ('d_buildtime', models.DateField()),
                ('seller', models.CharField(max_length=128)),
                ('shop_sence', models.CharField(max_length=128)),
                ('d_version_id', models.CharField(max_length=64)),
            ],
        ),
    ]
