# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-22 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liangyun_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FansData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fans', models.IntegerField(unique=True)),
                ('used', models.IntegerField(unique=True)),
                ('show', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineOne',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeMachine',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField()),
                ('machine', models.ManyToManyField(to='liangyun_app.MachineOne')),
            ],
        ),
        migrations.AddField(
            model_name='fansdata',
            name='machine',
            field=models.ManyToManyField(to='liangyun_app.MachineOne'),
        ),
        migrations.AddField(
            model_name='fansdata',
            name='time',
            field=models.ManyToManyField(to='liangyun_app.TimeMachine'),
        ),
    ]
