# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-22 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liangyun_app', '0002_auto_20181222_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineone',
            name='machine_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
